export const CommonStrings = {
  home: 'Adoption',
  homes: 'Adopt',
  donation: 'Donations',
  setting: 'Settings',
  homeHeading: 'Adopt a pup',
  donationHeading: 'Make a difference',
  description: 'Descriptions',
  donate: 'Donate',
  help: 'Get help',
  feedback: 'Give us feedback',
  Legal: 'Legal',
  terms: 'Terms of service',
  profile: 'View profile',
  support: 'Support',
  listYourPup: 'List a pup',
  toTheReader: 'To the reader',
  privacy: 'Privacy ',
  softwareVersion: 'Software version',
  share: 'Share app',
  rate: 'Rate us',
  contact: 'Contact us',
  account: 'Account',
  welcome: 'Welcome Back!',
  missed: "You've been missed",
  signGoogle: 'Sign in with Google',

  // icons
  privacyIcon: 'lock-closed-outline',
  playstore: 'logo-google-playstore',
  shareIcon: 'share-social-outline',
  mail: 'mail-outline',
  softIcons: 'build-outline',
  feedbackIcon: 'ear-outline',
  paw: 'paw-outline',
  people: 'people-circle',
};
