export const CommonStrings = {
  home: 'Adoption',
  homes: 'Adopt',
  donation: 'Donations',
  setting: 'Settings',
  homeHeading: 'Adopt a pup',
  donationHeading: 'Make a difference',
  description: 'Descriptions',
  donate: 'Donate',
  help: 'Get help',
  feedback: 'Give us feedback',
  Legal: 'Legal',
  terms: 'Terms of service',
  profile: 'View profile',
  support: 'Support',
  listYourPup: 'List a pup',
  toTheReader: 'To the reader',
  privacy: 'Privacy ',
  softwareVersion: 'Software version',
  share: 'Share app',
  rate: 'Rate us',
  contact: 'Contact us',
  account: 'Account',
  welcome: 'Welcome Back!',
  missed: "You've been missed",
  signGoogle: 'Sign in with Google',
  signOut: 'Sign out',
  logoutIcon: 'log-out',
  pageNotFound: 'Error 404',
  pageNotFoundMessage:
    "Maybe our Doggo has broken this page. Let's head back and try that again. Truth is out there..",
  letsGoHome: "Let's go home",
  sex: 'Sex',
  age: 'Age',
  temper: 'Temper',
  viewProfile: 'View Profile',
  summary: 'Summary',
  healthHistory: 'Health History',
  commonCancel: 'Cancel',
  commonSave: 'Search',
  commonFilter: 'Filters',
  chooseYourPet: 'Choose Your Pet',
  chooseYourLocation: 'Choose Your Location',
  choosePet: 'Pet',
  chooseLocation: 'Location',
  adoptMe: 'Adopt Me',
  adopted: 'Taken',
  almostThere: 'Almost there!',
  contact: 'Contact Number',
  address: 'Your Address',
  commonUpdate: 'Update Profile',
  requested: 'Requested',
  thankYou: 'Thank you',
  thankYouMessage:
    'Your adoption interest has been recorded. One of our representative will reach out to you soon. Until then you can sit back and relax. ',
  thanksForYourDonation: 'Thanks for your donation!',
  thanksForYourDonationMessage:
    'Your donation has been recorded and it will make big impact on these animals. You will soon recieve an email from our organization confirming your donation. If you have any query reach out to us.',
  goToDonations: 'Go to donations',
  failedTransaction: 'Transaction Failed',
  transactionFailedMessage:
    'We are sorry, but your current payment method could not be processed. Please reach out to us or try again. Sorry for the inconvenience',
  tryAgain: 'Try Again',
  // icons names
  privacyIcon: 'lock-closed-outline',
  playstore: 'logo-google-playstore',
  shareIcon: 'share-social-outline',
  mail: 'mail-outline',
  softIcons: 'build-outline',
  feedbackIcon: 'ear-outline',
  paw: 'paw-outline',
  people: 'people-circle',
};
